### PR TITLE
Level design - fixed buying items + global health + new title

### LINKED ISSUE #64: Level Design
This will be for creating level boarders, decorating scenes with trees or tables.

### PR DESCRIPTION
**Pull request by WillBennett2**
Fixed buggy buying with items
global health between levels 
New title added - no back drop 

image

dont think I have missed anything

### CODE REVIEW

File: Roche-Engine/Levels/GameManager.cpp [hunk 1]
```diff
@@ -94,6 +96,11 @@ void GameManager::HandleEvent(Event* event)
 	case EVENTID::PlayMainMenuMusic:
 		AudioEngine::GetInstance()->PlayAudio("MusicMenu", "MainMenuMusic", MUSIC);
 		break;
+	case EVENTID::SetPlayerHealth:
+		m_fSaveCurrentHealth = *static_cast<float*>(event->GetData());
+		break;
+	case EVENTID::LoadPlayerHealth:
+		EventSystem::Instance()->AddEvent(EVENTID::GetPlayerHealth,&m_fSaveCurrentHealth);
 	case EVENTID::UpdateBrightness:
```
Comment (kyle-robinson) [inline Roche-Engine/Levels/GameManager.cpp:104]: _NOTE: Add ```break``` here._

**Review by kyle-robinson — APPROVED** [review]
Great work Will 😎 👍🏻
